---
version: '3'
services:
  train:
    image: baddam355/train
    port:
      - 80:80
    deploy:
      replicas: 3

  movies:
    image: baddam355/movies
    port:
      - 81:80
    deploy:
      replicas: 3

  dth:
    image: baddam355/dth
    port:
      - 82:80
    deploy:
      replicas: 3
       
